repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        name: "all: ensure that files end with one newline"
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: "python: check for unused imports or variables"
        args:
          - "--select=F401,F821,F841"
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: "Python: sort imports"
        args:
          - "--profile=black"
          - "-o=numpy,pandas"
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: "python: format files"
