name: setup
description: installs dependencies & naz project
inputs:
  compute_instance:
    description: name of compute instance
    required: true
runs:
  using: "composite"
  steps:
    - name: cache linux
      uses: actions/cache@v3
      with:
        key: linux-cache
        path: ${{runner.temp}}/cache-linux
    - name: cache venv
      uses: actions/cache@v3
      with:
        key: venv-cache-${{ hashFiles('**/uv.lock') }}
        path: .venv
    - run: az extension add -n ml -y
      shell: bash
    - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      shell: bash
    - run: uv venv -p 3.11.10
      shell: bash
    - run: source .venv/bin/activate
      shell: bash
    - run: uv pip install -r pyproject.toml
      shell: bash
    - run: uv pip install .
      shell: bash
    - name: create compute instance
      run: az ml compute create -w ${GITHUB_REPOSITORY#*/}-ws -g ${GITHUB_REPOSITORY#*/}-rg -n ${inputs.compute_instance} --size Standard_E4ds_v4 --type ComputeInstance
      shell: bash
      continue-on-error: true
