name: setup
description: installation of virtual environment
inputs:
  compute_instance:
    description: name of compute instance
    required: true
runs:
  using: "composite"
  steps:
    - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      shell: bash
    - name: cache venv
      id: cache-venv
      uses: actions/cache@v3
      with:
        key: venv-cache-${{ hashFiles('**/uv.lock') }}
        path: .venv
    - if: ${{ steps.cache-venv.outputs.cache-hit != 'true' }}
      run: uv venv -p 3.11.10
      shell: bash
    - run: source .venv/bin/activate
      shell: bash
    - if: ${{ steps.cache-venv.outputs.cache-hit != 'true' }}
      run: uv pip install -r pyproject.toml && pip install .
      shell: bash
