name: setup
description: installs uv, venv, dependencies, and naz project
runs:
  using: "composite"
  steps:
    - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      shell: bash
    - run: uv venv -p 3.11.10
      shell: bash
    - run: source .venv/bin/activate
      shell: bash
    - run: uv pip install -r pyproject.toml && uv pip install .
      shell: bash
