name: pipeline-model-training
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: install az ml
      run: az extension add -n ml -y
    - name: install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: install venv
      run: uv venv -p 3.11.10
    - name: activate venv
      run: source .venv/bin/activate
    - name: install dependencies
      run: uv pip install -r pyproject.toml
      working-directory: .
    - name: install naz project
      run: uv run pip install .
    - name: start compute instance
      run: az ml compute start -n numeraz-ci01 -w numeraz-ws -g numeraz-rg
    - name: run job
      run: naz pipeline model_training
    - name: stop compute instance
      run: az ml compute start -n numeraz-ci01 -w numeraz-ws -g numeraz-rg
