name: pipeline-model-training
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: install az ml
      run: az extension add -n ml -y
    - name: setup
      run: bash setup_naz.sh
    - name: start compute instance
      run: az ml compute start -n numeraz-ci01 -w numeraz-ws -g numeraz-rg
    - name: run job
      run: naz pipeline model_training
    - name: stop compute instance
      run: az ml compute stop -n numeraz-ci01
