name: pytests
on:
  workflow_dispatch:
    inputs:
      compute_instance_name:
        default: gha-ci
        type: string
        required: false
  # push:
  #   paths:
  #     - "**.py"
  #     - "src/**"
jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      compute_instance_name: ${{github.event.inputs.compute_instance_name}}
    secrets: inherit
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - run: uv run pytest tests/core
