name: pytests
on:
  workflow_call:
  push:
    paths:
      - "**.py"
      - "src/**"
jobs:
  test-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: domreichl/numeraz@main
      - run: uv run pytest tests/core
