name: unit-tests
on:
  push:
    paths:
      - "**.py"
      - "src/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - run: uv venv -p 3.11.10
    - run: source .venv/bin/activate
    - run: uv pip install -r pyproject.toml
    - run: uv pip install .
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: pytest
