name: pytests
on:
  workflow_dispatch:
    inputs:
      compute_instance_name:
        default: gha-ci
        type: string
        required: false
  # push:
  #   paths:
  #     - "**.py"
  #     - "src/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: action.yml
        with:
          compute_instance_name: ${{github.event.inputs.compute_instance_name}}
      - run: uv run pytest tests/core
