name: pytests
on:
  workflow_dispatch:
    inputs:
      compute_instance_name:
        default: gha-ci
        type: string
        required: false
  # push:
  #   paths:
  #     - "**.py"
  #     - "src/**"
jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    env:
      SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
      COMPUTE_INSTANCE: ${{github.event.inputs.compute_instance_name}}
      RESOURCE_GROUP: ${{vars.RESOURCE_GROUP}}
      WORKSPACE_NAME: ${{vars.WORKSPACE_NAME}}
      ENVIRONMENT_NAME: ${GITHUB_REPOSITORY#*/}-env
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - uses: domreichl/numeraz@main
        with:
          compute_instance_name: ${{github.event.inputs.compute_instance_name}}
      - run: uv run pytest tests/core
      - name: write .env file
        run: |
          cat <<EOF > .env
          SUBSCRIPTION_ID=${SUBSCRIPTION_ID}
          COMPUTE_INSTANCE=${COMPUTE_INSTANCE}
          RESOURCE_GROUP=${RESOURCE_GROUP}
          WORKSPACE_NAME=${WORKSPACE_NAME}
          ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
          EOF
